const products = [
  {id:'velocity',name:'VELOCITY 01',desc:'Lightweight lace-up work shoe',price:'$59.99',type:'lace',tag:'BEST SELLER',image:'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1000&q=82',tone:'red'},
  {id:'essential',name:'ESSENTIAL 02',desc:'All-shift cushioned work shoe',price:'$64.99',type:'lace',tag:'NEW',image:'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=1000&q=82',tone:'light'},
  {id:'command',name:'COMMAND 03',desc:'Heavy-duty traction work shoe',price:'$69.99',type:'pro',tag:'PRO SERIES',image:'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=1000&q=82',tone:'dark'},
  {id:'service',name:'SERVICE 04',desc:'Easy-on hospitality slip-on',price:'$54.99',type:'slipon',tag:'SLIP-ON',image:'https://images.unsplash.com/photo-1491553895911-0055eca6402d?auto=format&fit=crop&w=1000&q=82',tone:'light'},
  {id:'guard',name:'GUARD 05',desc:'Reinforced professional work shoe',price:'$74.99',type:'pro',tag:'HEAVY DUTY',image:'https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&w=1000&q=82',tone:'red'},
  {id:'daily',name:'DAILY 06',desc:'Easy-clean work slip-on',price:'$57.99',type:'slipon',tag:'EVERYDAY',image:'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?auto=format&fit=crop&w=1000&q=82',tone:'dark'}
];
const amazon = p => `https://www.amazon.com/s?k=${encodeURIComponent(`JEAVTIFL ${p.name} work shoes`)}`;
const card = p => `<article class="product-card"><a href="product.html?id=${p.id}" aria-label="View ${p.name}"><div class="product-image ${p.tone}"><span class="tag">${p.tag}</span><img src="${p.image}" alt="JEAVTIFL ${p.name} ${p.desc}" width="1000" height="900" loading="lazy"></div><div class="product-info"><div><h3>${p.name}</h3><p>${p.desc}</p></div><strong>${p.price}</strong></div></a><a class="card-buy" href="${amazon(p)}" target="_blank" rel="noopener sponsored">BUY ON AMAZON ↗</a></article>`;
const catalog=document.querySelector('#catalog');
function renderProducts(filter='all'){if(catalog){const list=filter==='all'?products:products.filter(p=>p.type===filter);catalog.innerHTML=list.map(card).join('')}}
renderProducts();
const featured=document.querySelector('#featured-products');if(featured) featured.innerHTML=products.slice(0,3).map(card).join('');
document.querySelectorAll('.filters button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelector('.filters .active')?.classList.remove('active');btn.classList.add('active');renderProducts(btn.dataset.filter)}));
const detail=document.querySelector('#product-detail');if(detail){const p=products.find(x=>x.id===new URLSearchParams(location.search).get('id'))||products[0];document.title=`${p.name} Work Shoe | JEAVTIFL`;detail.innerHTML=`<section class="product-detail"><div class="detail-gallery ${p.tone}"><span class="tag">${p.tag}</span><img src="${p.image}" alt="${p.name} ${p.desc}" width="1200" height="1100"></div><div class="detail-copy"><a class="back-link" href="products.html">← ALL FOOTWEAR</a><span class="eyebrow dark">JEAVTIFL / PROFESSIONAL SERIES</span><h1>${p.name}</h1><p class="detail-desc">${p.desc} engineered for confident movement and dependable comfort in demanding workplaces.</p><div class="detail-price">${p.price}<span>Price and availability shown on Amazon may vary.</span></div><div class="sizes"><b>SELECT SIZE ON AMAZON</b><div>US 6–13 · STANDARD WIDTH</div></div><a class="amazon-btn" href="${amazon(p)}" target="_blank" rel="noopener sponsored"><b>amazon</b><span>BUY NOW ↗</span></a><p class="fulfill">Purchases are completed and fulfilled on Amazon. Amazon's current shipping and return terms apply.</p><ul class="benefit-list"><li><b>JEAVGRIP™ TRACTION</b><span>Multi-directional rubber outsole engineered for workplace surfaces.</span></li><li><b>ALL-SHIFT SUPPORT</b><span>Responsive cushioning and a stable heel platform.</span></li><li><b>EASY-CLEAN DESIGN</b><span>Low-maintenance upper made for fast post-shift care.</span></li></ul></div></section><section class="detail-banner"><span>MADE FOR</span><div>RESTAURANTS · KITCHENS · FOOD PRODUCTION · HOSPITALITY</div></section>`}
const toast=document.querySelector('.toast');function showToast(m){if(!toast)return;toast.textContent=m;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2400)}
document.querySelector('.menu-toggle')?.addEventListener('click',e=>{const h=e.currentTarget.closest('.site-header');h.classList.toggle('menu-open');e.currentTarget.setAttribute('aria-expanded',String(h.classList.contains('menu-open')))});
document.querySelector('.announcement button')?.addEventListener('click',e=>e.currentTarget.parentElement.remove());
document.querySelectorAll('.accordion button').forEach(btn=>btn.addEventListener('click',()=>{const a=btn.parentElement;a.classList.toggle('open');btn.setAttribute('aria-expanded',String(a.classList.contains('open')))}));
document.querySelector('.newsletter-form')?.addEventListener('submit',e=>{e.preventDefault();showToast('You’re on the list. Welcome to JEAVTIFL.');e.target.reset()});
document.querySelector('.contact-form')?.addEventListener('submit',e=>{e.preventDefault();showToast('Message received. We’ll be in touch soon.');e.target.reset()});
if('IntersectionObserver' in window){const o=new IntersectionObserver(es=>es.forEach(x=>x.isIntersecting&&x.target.classList.add('visible')),{threshold:.1});document.querySelectorAll('.reveal').forEach(x=>o.observe(x))}else document.querySelectorAll('.reveal').forEach(x=>x.classList.add('visible'));
